name: micro_app_core
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  micro_app_auth: 
    git:    
      url: https://github.com/mgarcia88/micro_app_auth.git
      ref: v1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: